#!/bin/bash

# colors
bold="$(tput bold)"
magenta="$(tput setaf 5)"
green="$(tput setaf 2)"
white="$(tput setaf 7)"
blue="$(tput setaf 4)"
red="$(tput setaf 1)"
black="$(tput setaf 0)"
yellow="$(tput setaf 3)"
cyan="$(tput setaf 6)" 

c0="${white}"
c1="${magenta}"
c2="${green}"
c3="${blue}"
c4="${red}"
c5="${yellow}"
c6="${cyan}"

# check distro info 
distro=$(source /etc/os-release && echo $PRETTY_NAME)

#kernel info
kernel="$(uname -r)"

#current shell
shell="$(basename $SHELL)"

# uptime
system_uptime="$(uptime -p | sed 's/up//')"

# check the memory
mem=$(free -m | sed -n 's/^Mem:\s\+[0-9]\+\s\+\([0-9]\+\)\s.\+/\1/p')

# output 
echo "${c0}           ╓────────────────────────────────────╖"
echo "${c0}           ║ ${c1}os${c0}   $distro            ║"
echo "${c0}           ║ ${c2}kr${c0}   $kernel║"
echo "${c0}           ║ ${c4}sh${c0}   $shell                          ║"
echo "${c0}           ║ ${c5}up${c0}  $system_uptime           ║"
echo "${c0}           ║ ${c6}ram${c0}  $mem MB                        ║"
echo "${c0}            \   ────────────────────────────────╜"
echo "${c0}             \ /"
echo "${c0}              V"
echo "${c2}     ▀▄   ▄▀    "
echo "${c2}    ▄█▀███▀█▄   "
echo "${c2}   █▀███████▀█  "
echo "${c2}   █ █▀▀▀▀▀█ █  "
echo "${c2}      ▀▀ ▀▀     "
